# Generated by Django 5.1.1 on 2024-10-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_status_alter_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('ASGD', 'Assigned'), ('PRGS', 'In progress'), ('SPND', 'Suspended'), ('CMPL', 'Completed')], default='ASGD', max_length=4),
        ),
    ]
