# Generated by Django 5.1.1 on 2024-10-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('AS', 'Assigned'), ('PR', 'In progress'), ('SP', 'Suspended'), ('CM', 'Completed')], default='AS', max_length=2),
        ),
    ]
