# Generated by Django 5.1.1 on 2024-10-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_labor_intensity',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
