# Generated by Django 5.1.1 on 2024-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
